name: Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          check-latest: true

      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v3

      - name: Test on Ubuntu
        run: ./gradlew assemble check --no-build-cache --no-daemon --stacktrace

  all-checks:
    if: always()
    runs-on: ubuntu-latest
    needs:
      - test-ubuntu

    steps:
      - name: require that all other jobs have passed
        uses: re-actors/alls-green@release/v1
        with:
          allowed-skips: publish
          jobs: ${{ toJSON(needs) }}